In [1]:
print("hello world")

hello world


In [2]:
import torch
print(torch.__version__)

2.7.0+cpu


In [3]:
##So, what are Tensors? In simple terms, Tensors are multi-dimensional matrices filled with elements of the same data type.
##They are the basic data structures of PyTorch which are used to build various types of neural networks.

In [4]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [5]:
print("shape : ",x.shape)
print("Dtype : ",x.dtype)
print("Device : ",x.device)

shape :  torch.Size([3])
Dtype :  torch.int64
Device :  cpu


In [6]:
y = torch.tensor([4,5,6])
##  arthematic operations
print(f'Addition : {x+y}')
print(f'Substraction : {x-y}')
print(f'Multiplication : {x*y}')
print(f'Division : {x/y}')

Addition : tensor([5, 7, 9])
Substraction : tensor([-3, -3, -3])
Multiplication : tensor([ 4, 10, 18])
Division : tensor([0.2500, 0.4000, 0.5000])


In [7]:
z = x.view(3,1)
print("Reshaped tensor : ",z)

Reshaped tensor :  tensor([[1],
        [2],
        [3]])


In [8]:
concat = torch.cat((x,y))
print("Concatinated Tensor : ",concat)

Concatinated Tensor :  tensor([1, 2, 3, 4, 5, 6])


In [9]:
a = torch.tensor([1.,2.,3.] ,requires_grad = True)
a

tensor([1., 2., 3.], requires_grad=True)

In [10]:
b = a*2
print(b)

tensor([2., 4., 6.], grad_fn=<MulBackward0>)


In [11]:
c = b.mean()
print(c)

tensor(4., grad_fn=<MeanBackward0>)


In [12]:
c.backward()
print("Gradients : ",a.grad)

Gradients :  tensor([0.6667, 0.6667, 0.6667])


In [13]:
# Check CUDA availability
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

# Moving Tensors to the GPU
x = x.to(device)
print('New device:', x.device)

New device: cpu


In [14]:
from torch.utils.data import Dataset
from PIL import Image

class CustomImageDataset(Dataset):
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx])
        label = self.labels[idx]

        if self.transform:
            image = self.transform(image)

        return image, label

In [15]:
from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,))])

# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)

100%|██████████| 9.91M/9.91M [00:14<00:00, 691kB/s] 
100%|██████████| 28.9k/28.9k [00:00<00:00, 47.6kB/s]
100%|██████████| 1.65M/1.65M [00:04<00:00, 401kB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 529kB/s]


In [16]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

In [17]:
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

In [18]:
from torch.utils.data import DataLoader

trainloader = DataLoader(trainset, batch_size=64, shuffle=True)