In [5]:
import torch.nn as nn
import numpy as np
import torch

In [6]:
inputs = np.array([
    [73,67,43],[91,88,64],[87,134,58],
    [102,43,37],[69,96,70],[73,67,43],
    [91,88,64],[87,134,58],[102,43,37],
    [69,96,70],[73,67,43],[91,88,64],
    [87,134,58],[102,43,37],[69,96,70]
    
],dtype = 'float32')

targets = np.array([
    [56,70],[81,101],[119,133],
    [22,37],[103,119],[56,70],
    [81,101],[119,133],[22,37],
    [103,119],[56,70],[88,101],
    [119,133],[22,37],[103,119]
],dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
inputs , targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 88., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [10]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [11]:
from torch.utils.data import DataLoader
batch_size =5
train_dl = DataLoader(train_ds , batch_size,shuffle=True)

In [12]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [103., 119.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
## define model

model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3139, -0.4425, -0.2999],
        [ 0.3979, -0.3858, -0.4647]], requires_grad=True)
Parameter containing:
tensor([0.1489, 0.1701], requires_grad=True)


In [14]:
## parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3139, -0.4425, -0.2999],
         [ 0.3979, -0.3858, -0.4647]], requires_grad=True),
 Parameter containing:
 tensor([0.1489, 0.1701], requires_grad=True)]

In [15]:
preds = model(inputs)
preds

tensor([[ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366],
        [ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366],
        [ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366]], grad_fn=<AddmmBackward0>)

In [16]:
## loss function
import torch.nn.functional as  F
loss_fn = F.mse_loss

In [17]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(21767.8730, grad_fn=<MseLossBackward0>)


In [18]:
## define optimizer

opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [27]:
## train the model
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for xb , yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            if (epoch+1) % 10 ==0:
                print('Epoch [{}/{}],Loss : {:.4f}'.format(epoch+1,num_epochs,loss.item()))
                

In [28]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100],Loss : 141.1031
Epoch [10/100],Loss : 156.7168
Epoch [10/100],Loss : 327.5796
Epoch [20/100],Loss : 154.5039
Epoch [20/100],Loss : 56.4263
Epoch [20/100],Loss : 241.7652
Epoch [30/100],Loss : 113.5218
Epoch [30/100],Loss : 88.6938
Epoch [30/100],Loss : 150.9754
Epoch [40/100],Loss : 85.2235
Epoch [40/100],Loss : 89.7711
Epoch [40/100],Loss : 87.5880
Epoch [50/100],Loss : 69.0556
Epoch [50/100],Loss : 66.4559
Epoch [50/100],Loss : 78.6693
Epoch [60/100],Loss : 80.4604
Epoch [60/100],Loss : 77.0572
Epoch [60/100],Loss : 13.3836
Epoch [70/100],Loss : 43.7941
Epoch [70/100],Loss : 52.0416
Epoch [70/100],Loss : 51.9312
Epoch [80/100],Loss : 38.2488
Epoch [80/100],Loss : 58.0063
Epoch [80/100],Loss : 27.6790
Epoch [90/100],Loss : 36.0886
Epoch [90/100],Loss : 49.0550
Epoch [90/100],Loss : 25.2697
Epoch [100/100],Loss : 31.4885
Epoch [100/100],Loss : 34.0114
Epoch [100/100],Loss : 32.6309


In [29]:
preds = model(inputs)
preds

tensor([[ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647],
        [ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647],
        [ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647]], grad_fn=<AddmmBackward0>)

In [30]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 88., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])