In [1]:
print("Hello world")

Hello world


In [3]:
import torch
import numpy as np


In [5]:
## input (temp,rainfall,humidity)
inputs = np.array([[72,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype = 'float32')

In [6]:
## targets (apples,oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]],dtype='float32')

In [7]:
## convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 72.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
## Linear regression model  from scratch
w = torch.randn(2,3,requires_grad = True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.0257,  0.4217, -0.7377],
        [ 0.9006, -0.1074,  0.8907]], requires_grad=True)
tensor([-1.6620, -0.9193], requires_grad=True)


In [ ]:
## defining our model
def model(x):
    return x @ w.t() + b

## @   represents matrix multiplication

In [12]:
preds =  model(inputs)
print(preds)

tensor([[ -6.9772,  95.0222],
        [-14.1009, 128.5811],
        [  9.8276, 114.6928],
        [-13.4430, 119.2733],
        [-14.5883, 113.2534]], grad_fn=<AddBackward0>)


In [13]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [20]:
## MSE loss
def mse(t1,t2):
    diff =  t1 - t2
    return torch.sum(diff * diff)/diff.numel()
 
## diff.numel means the number of element in tensor

In [21]:
loss = mse(preds,targets)
print(loss)

tensor(4853.6045, grad_fn=<DivBackward0>)


In [22]:
# compute gradients
loss.backward()

In [24]:
print(w)
print(w.grad)

tensor([[-0.0257,  0.4217, -0.7377],
        [ 0.9006, -0.1074,  0.8907]], requires_grad=True)
tensor([[-6883.0630, -8005.9961, -4933.8096],
        [ 2142.8223,   927.3060,   884.2347]])


In [26]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [27]:
w,b

(tensor([[-0.0257,  0.4217, -0.7377],
         [ 0.9006, -0.1074,  0.8907]], requires_grad=True),
 tensor([-1.6620, -0.9193], requires_grad=True))

In [28]:
preds = model(inputs)
print(preds)

tensor([[ -6.9772,  95.0222],
        [-14.1009, 128.5811],
        [  9.8276, 114.6928],
        [-13.4430, 119.2733],
        [-14.5883, 113.2534]], grad_fn=<AddBackward0>)


In [29]:
## calculate the loss
loss = mse(preds,targets)
print(loss)

tensor(4853.6045, grad_fn=<DivBackward0>)


In [30]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-6883.0630, -8005.9961, -4933.8096],
        [ 2142.8223,   927.3060,   884.2347]])
tensor([-84.0564,  22.1646])


In [32]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad *1e-5
    w.grad.zero_()
    b.grad.zero_()

In [33]:
print(w)
print(b)

tensor([[ 0.0431,  0.5018, -0.6884],
        [ 0.8791, -0.1167,  0.8818]], requires_grad=True)
tensor([-1.6612, -0.9195], requires_grad=True)


In [41]:
preds = model(inputs)
loss = mse(preds , targets)
print(loss)

tensor(2682.8911, grad_fn=<DivBackward0>)


In [43]:
for i in range(100):
    pred = model(inputs)
    loss = mse(pred,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [46]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(287.0280, grad_fn=<DivBackward0>)


In [47]:
preds

tensor([[ 60.4133,  76.0062],
        [ 76.8772, 105.7958],
        [125.5234, 111.9557],
        [ 41.3775,  72.5636],
        [ 80.4691, 107.1081]], grad_fn=<AddBackward0>)

In [48]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])