In [5]:
import torch.nn as nn
import numpy as np
import torch

In [6]:
inputs = np.array([
    [73,67,43],[91,88,64],[87,134,58],
    [102,43,37],[69,96,70],[73,67,43],
    [91,88,64],[87,134,58],[102,43,37],
    [69,96,70],[73,67,43],[91,88,64],
    [87,134,58],[102,43,37],[69,96,70]
    
],dtype = 'float32')

targets = np.array([
    [56,70],[81,101],[119,133],
    [22,37],[103,119],[56,70],
    [81,101],[119,133],[22,37],
    [103,119],[56,70],[88,101],
    [119,133],[22,37],[103,119]
],dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
inputs , targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 88., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [10]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [11]:
from torch.utils.data import DataLoader
batch_size =5
train_dl = DataLoader(train_ds , batch_size,shuffle=True)

In [12]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [103., 119.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
## define model

model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3139, -0.4425, -0.2999],
        [ 0.3979, -0.3858, -0.4647]], requires_grad=True)
Parameter containing:
tensor([0.1489, 0.1701], requires_grad=True)


In [14]:
## parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3139, -0.4425, -0.2999],
         [ 0.3979, -0.3858, -0.4647]], requires_grad=True),
 Parameter containing:
 tensor([0.1489, 0.1701], requires_grad=True)]

In [15]:
preds = model(inputs)
preds

tensor([[ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366],
        [ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366],
        [ -65.3057,  -16.6104],
        [ -86.5451,  -27.3077],
        [-103.8430,  -43.8576],
        [ -61.9908,    6.9767],
        [ -84.9781,  -41.9366]], grad_fn=<AddmmBackward0>)

In [16]:
## loss function
import torch.nn.functional as  F
loss_fn = F.mse_loss

In [17]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(21767.8730, grad_fn=<MseLossBackward0>)


In [18]:
## define optimizer

opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [31]:
## train the model
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        ## train with batches of data
        for xb , yb in train_dl:
            ## 1. genearte predictions
            pred = model(xb)
            ## 2. Calculate the loss
            loss = loss_fn(pred,yb)
            ## 3. compute Gradients
            loss.backward()
            ## 4. update parameters using gradients
            opt.step()
            ## 5. Reset the gradient to zero
            opt.zero_grad()
            if (epoch+1) % 10 ==0:
                print('Epoch [{}/{}],Loss : {:.4f}'.format(epoch+1,num_epochs,loss.item()))
                

In [32]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100],Loss : 50.2911
Epoch [10/100],Loss : 22.4513
Epoch [10/100],Loss : 19.6945
Epoch [20/100],Loss : 28.3476
Epoch [20/100],Loss : 22.3870
Epoch [20/100],Loss : 30.4304
Epoch [30/100],Loss : 13.3411
Epoch [30/100],Loss : 37.7640
Epoch [30/100],Loss : 26.8442
Epoch [40/100],Loss : 24.8398
Epoch [40/100],Loss : 21.3261
Epoch [40/100],Loss : 23.1129
Epoch [50/100],Loss : 23.9513
Epoch [50/100],Loss : 19.4781
Epoch [50/100],Loss : 21.7803
Epoch [60/100],Loss : 32.0399
Epoch [60/100],Loss : 10.5509
Epoch [60/100],Loss : 20.0356
Epoch [70/100],Loss : 15.1363
Epoch [70/100],Loss : 13.6149
Epoch [70/100],Loss : 31.8895
Epoch [80/100],Loss : 9.8638
Epoch [80/100],Loss : 17.6201
Epoch [80/100],Loss : 28.4948
Epoch [90/100],Loss : 22.1947
Epoch [90/100],Loss : 9.0855
Epoch [90/100],Loss : 20.7417
Epoch [100/100],Loss : 12.6764
Epoch [100/100],Loss : 24.8284
Epoch [100/100],Loss : 14.5384


In [29]:
preds = model(inputs)
preds

tensor([[ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647],
        [ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647],
        [ 58.4090,  71.7288],
        [ 81.1421,  96.8196],
        [121.4960, 139.7606],
        [ 26.0811,  44.3572],
        [ 97.0082, 108.1647]], grad_fn=<AddmmBackward0>)

In [33]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 88., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])