In [1]:
print("Hello world")

Hello world


In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
## A tensor is a numbber, vector, matrices or any n-dimensional array

In [4]:
print(t1)
print(t1.dtype)

tensor(4.)
torch.float32


In [5]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix 
t3 = torch.tensor([[5.,6]
                   ,[7,8],
                   [9,10]])

t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3 - dimensional array
t4 = torch.tensor([[[11,12,13,14]
                    ,[13,14,15,16]],[
                       [21,22,23,24],
                       [31,32,34,35] 
                    ]])

t4

tensor([[[11, 12, 13, 14],
         [13, 14, 15, 16]],

        [[21, 22, 23, 24],
         [31, 32, 34, 35]]])

In [8]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 4])


In [9]:
## tensor operations and gradients
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [10]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [11]:
y.backward()

In [12]:
print("dy/dx : ",x.grad)
print("dy/dw : ",w.grad)
print("dy/db : ",b.grad)

dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


In [13]:
## interoperation
import numpy as np
x = np.array([[1,3],[3,4.]])
x

array([[1., 3.],
       [3., 4.]])

In [14]:
y = torch.from_numpy(x)
y

tensor([[1., 3.],
        [3., 4.]], dtype=torch.float64)

In [15]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [16]:
z = y.numpy()
z

array([[1., 3.],
       [3., 4.]])

In [17]:
z.dtype

dtype('float64')